train:
  epochs: 500
  gpus: 1
  name: "test"

model:
  input_nc: 3
  output_nc: 3
  ngf: 64
  ndf: 64
  lr: 0.00002
  beta1: 0.5
  lambda_identity: 0.1
  lambda_cycle: 10

data:
  batch_size: 4
  num_workers: 0
  shuffle: True
  resize: [128, 128]
  crop_size: [128, 128]

  root_nyudv2: "C:\\Users\\appel\\Documents\\Project\\synthetic-image-segmentation\\data\\real\\nyudv2"
  root_bdsd500: "C:\\Users\\appel\\Documents\\Project\\synthetic-image-segmentation\\data\\real\\bdsd500"