train:
  epochs: 100
  gpus: [1]
  name: "unity - nyudv2 none/448"
  experiment: full size
  checkpoint_path: "D:\\Appel\\Improved Edge detection\\Synthetic-Image-Segmentation-with-Domain-Adaptation\\outputs\\2023-12-08\\10-02-19\\CycleGAN\\osv8el4j\\checkpoints\\epoch=8-step=18252.ckpt"
test:
  checkpoint_path: None

wandb: True

model:
  input_nc: 3
  output_nc: 3
  ngf: 64
  ndf: 64
  lr: 0.0002
  beta1: 0.5
  lambda_identity: 0.1
  lambda_cycle: 10

data:
  batch_size: 1
  num_workers: 0
  shuffle: True
  resize: None
  crop_size: [448, 448]

  root_nyudv2: "D:\\Appel\\Improved Edge detection\\Synthetic-Image-Segmentation-with-Domain-Adaptation\\data\\real\\nyudv2"
  root_bdsd500: "D:\\Appel\\Improved Edge detection\\Synthetic-Image-Segmentation-with-Domain-Adaptation\\data\\real\\bdsd500"

  dataset_a : "unity"
  dataset_b : "nyudv2"