train:
  name: 'Unity'
  epochs: 100
  gpus: 1

data:
  batch_size: 4
  num_workers: 0
  shuffle: True
  resize: None
  crop_size: [256, 256]

  root_nyudv2: "C:\\Users\\appel\\Documents\\Project\\synthetic-image-segmentation\\data\\real\\nyudv2"
  root_bdsd500: "C:\\Users\\appel\\Documents\\Project\\synthetic-image-segmentation\\data\\real\\bdsd500"

  dataset: "unity"

  domain_transfer: True
  checkpoint_path: 'D:\Appel\Improved Edge detection\Synthetic-Image-Segmentation-with-Domain-Adaptation\outputs\2023-11-16\18-17-50\CycleGAN\1ycnhgnn\checkpoints\epoch=199-step=405600.ckpt'
