train:
  name: Unity 448
  epochs: 100
  gpus: [1]

data:
  batch_size: 1
  num_workers: 0
  shuffle: True
  resize: None
  crop_size: [448, 448]

  root_nyudv2: "D:\\Appel\\Improved Edge detection\\Synthetic-Image-Segmentation-with-Domain-Adaptation\\data\\real\\nyudv2"
  root_bdsd500: "D:\\Appel\\Improved Edge detection\\Synthetic-Image-Segmentation-with-Domain-Adaptation\\data\\real\\bdsd500"

  dataset: "unity"

  domain_transfer: True
  checkpoint_path: 'D:\\Appel\\Improved Edge detection\\Synthetic-Image-Segmentation-with-Domain-Adaptation\\outputs\\2023-12-08\\17-32-43\\CycleGAN\\49zod04z\\checkpoints\\epoch=99-step=202800.ckpt'
