train:
  name: 'test'
  epochs: 20
  gpus: 1

data:
  batch_size: 4
  num_workers: 0
  shuffle: True
  resize: [256, 256]
  crop_size: [256, 256]

  root_nyudv2: "C:\\Users\\appel\\Documents\\Project\\synthetic-image-segmentation\\data\\real\\nyudv2"
  root_bdsd500: "C:\\Users\\appel\\Documents\\Project\\synthetic-image-segmentation\\data\\real\\bdsd500"