train:
  name: 'Unity'
  epochs: 100
  gpus: 1

data:
  batch_size: 4
  num_workers: 0
  shuffle: True
  resize: None
  crop_size: [256, 256]

  root_nyudv2: "C:\\Users\\appel\\Documents\\Project\\synthetic-image-segmentation\\data\\real\\nyudv2"
  root_bdsd500: "C:\\Users\\appel\\Documents\\Project\\synthetic-image-segmentation\\data\\real\\bdsd500"

  dataset: "unity"

  domain_transfer: True
  checkpoint_path: 'C:\Users\appel\Documents\Project\synthetic-image-segmentation\outputs\2023-09-04\14-39-16\CycleGAN\rtufrsre\checkpoints\epoch=1-step=1016.ckpt'
